CREATE TABLE Followers (
    FollowerID UNIQUEIDENTIFIER FOREIGN KEY REFERENCES Users(UserID) ON DELETE CASCADE,
    FollowingID UNIQUEIDENTIFIER FOREIGN KEY REFERENCES Users(UserID) ON DELETE CASCADE,
    FollowedAt DATETIME DEFAULT GETUTCDATE(),
    PRIMARY KEY (FollowerID, FollowingID)
);