CREATE TABLE Media (
    MediaID UNIQUEIDENTIFIER PRIMARY KEY DEFAULT NEWID(),
    UserID UNIQUEIDENTIFIER FOREIGN KEY REFERENCES Users(UserID) ON DELETE CASCADE,
    TweetID UNIQUEIDENTIFIER NULL FOREIGN KEY REFERENCES Tweets(TweetID) ON DELETE CASCADE,
    DirectMessageID UNIQUEIDENTIFIER NULL FOREIGN KEY REFERENCES DirectMessages(MessageID) ON DELETE CASCADE,
    MediaURL NVARCHAR(512) NOT NULL,
    MediaType NVARCHAR(50) NOT NULL, -- (image, video, gif)
    UploadedAt DATETIME DEFAULT GETUTCDATE()
);