CREATE TABLE Tweets (
    TweetID UNIQUEIDENTIFIER PRIMARY KEY DEFAULT NEWID(),
    UserID UNIQUEIDENTIFIER FOREIGN KEY REFERENCES Users(UserID) ON DELETE CASCADE,
    TweetText NVARCHAR(280) NOT NULL,
    MediaURL NVARCHAR(512) NULL,
    CreatedAt DATETIME DEFAULT GETUTCDATE(),
    RetweetCount INT DEFAULT 0,
    LikeCount INT DEFAULT 0
);