CREATE TABLE TweetHashtags (
    TweetID UNIQUEIDENTIFIER FOREIGN KEY REFERENCES Tweets(TweetID) ON DELETE CASCADE,
    HashtagID UNIQUEIDENTIFIER FOREIGN KEY REFERENCES Hashtags(HashtagID) ON DELETE CASCADE,
    PRIMARY KEY (TweetID, HashtagID)
);